package com.agentflow.domain.model

enum class AgentStatus { READY, THINKING, WAITING, WAITING_FOR_PROVIDER, ERROR, DISABLED, RATE_LIMITED }
enum class RulePriority { LOW, NORMAL, HIGH, CRITICAL }
enum class ReferenceType { FILE, FOLDER, GITHUB, TEXT }
enum class InclusionMode { ALWAYS, RELEVANT, NEVER }
enum class MissionStatus {
    CREATED, RESEARCHING, PLANNING, WAITING_FOR_USER, EXECUTING, REVIEWING,
    REVISION_REQUIRED, APPROVED, ESCALATED, PAUSED, FAILED, CANCELLED
}
enum class TaskStatus {
    PENDING, READY, RUNNING, WAITING_FOR_DEPENDENCY, WAITING_FOR_USER,
    WAITING_FOR_AGENT, RETRYING, BLOCKED, COMPLETED, FAILED, CANCELLED, SKIPPED
}
enum class Priority { LOW, NORMAL, HIGH, CRITICAL }
enum class CreatedByType { USER, AGENT, SYSTEM, INSPECTOR, ENGINE }
enum class DependencyType { REQUIRED, OPTIONAL }
enum class ActorType { USER, AGENT, SYSTEM, INSPECTOR, ENGINE }
enum class MessageType { TASK, RESPONSE, ROUTE, REVIEW, USER_INPUT_REQUEST, ERROR, SYSTEM_EVENT }
enum class ReviewStatus { PENDING, APPROVED, REJECTED, ESCALATED }
enum class Severity { NONE, LOW, MEDIUM, HIGH, CRITICAL }
enum class ArtifactType {
    IMPLEMENTATION_PLAN, RESEARCH_REPORT, ARCHITECTURE_PLAN, CODE_PATCH,
    DESIGN_SPEC, TEST_PLAN, FINAL_REPORT
}
enum class MissionEventType {
    MISSION_CREATED, MISSION_PLANNING, MISSION_STARTED, MISSION_REVIEWING, MISSION_ESCALATED, TASK_CREATED, TASK_ASSIGNED, TASK_STARTED,
    TASK_COMPLETED, TASK_FAILED, AGENT_MESSAGE_SENT, USER_INPUT_REQUIRED,
    USER_INPUT_RECEIVED, INSPECTOR_STARTED, INSPECTOR_APPROVED, INSPECTOR_REJECTED,
    TASK_REOPENED, ARTIFACT_CREATED, ARTIFACT_UPDATED, MISSION_PAUSED,
    MISSION_RESUMED, MISSION_COMPLETED, MISSION_FAILED, MISSION_CANCELLED
}
enum class ProviderId { GEMINI, GROQ, OPENROUTER }
enum class RetentionPolicy { DAYS_30, DAYS_90, FOREVER }
